import Navigation from '../../Components/Stateful/Navigation/Navigation';
import NextReduxProvider from '../../Providers/redux-provider';

export const metadata = {
  title: 'Search for products',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextReduxProvider>
          <Navigation />
          {children}
        </NextReduxProvider>
      </body>
    </html>
  );
}
